### ISSUE TITLE
Still active? 

### ISSUE THREAD

**Issue by STX2k** [MaggiWuerze/xddcwebloader#40]
Hey is this project still active? I would love to see an xdcc webclient.

Greets

**Comment by MaggiWuerze** [comment]
In theory yes, I'm still looking into getting over the issues my IRC library has with connection stability.
You can run it as is, you just have to be careful not to load too much too fast, as i have not yet implemented a max connection setting.

If you are interested in contributing I'd be happy to look at your PRs.
Your question definitely was good for my motivation to get at it again, thank you.

**Comment by STX2k** [comment]
Nice. This sounds good. Keep it up. I look forward to any updates 👍

**Comment by MaggiWuerze** [comment]
So I picked this up again, did you test what was available so far?

**Comment by MaggiWuerze** [comment]
@STX2k If you want you can try the release I created, would love some feedback
