### ISSUE TITLE
The space key does not work in the add bot field

### ISSUE THREAD

**Issue by reddeath68** [MaggiWuerze/xddcwebloader#60]

**Comment by MaggiWuerze** [comment]
Apparently this was caused by the Nav element surrounding the button and popover root. The error is fixed in master I just need to make some UI adjustments before creating a new release

**Comment by MaggiWuerze** [comment]
Fixed in [v0.5.3-BETA](https://github.com/MaggiWuerze/xddcwebloader/tree/v0.5.3-BETA)
